### ISSUE TITLE
"Error: Provider not set or invalid" (19.6.1 release)

### ISSUE THREAD

**Issue by frol** [crossbario/autobahn-js#435]
Since 19.6.1 I am having the following warnings:

```
WARNING: The XBR smart contracts are not yet depoyed to public networks. Please set XBR_DEBUG_TOKEN_ADDR manually.
WARNING: The XBR smart contracts are not yet depoyed to public networks. Please set XBR_DEBUG_NETWORK_ADDR manually.
(node:25170) UnhandledPromiseRejectionWarning: Error: Provider not set or invalid
    at Object.InvalidProvider (/mnt/storage/projects/near.ai/near-explorer/backend/node_modules/web3-core-helpers/src/errors.js:38:16)
    at RequestManager.send (/mnt/storage/projects/near.ai/near-explorer/backend/node_modules/web3-core-requestmanager/src/index.js:128:32)
    at sendRequest (/mnt/storage/projects/near.ai/near-explorer/backend/node_modules/web3-core-method/src/index.js:560:42)
    at Net.send [as getId] (/mnt/storage/projects/near.ai/near-explorer/backend/node_modules/web3-core-method/src/index.js:581:13)
    at Function.detectNetwork (/mnt/storage/projects/near.ai/near-explorer/backend/node_modules/truffle-contract/lib/contract/constructorMethods.js:133:54)
    at Function.at (/mnt/storage/projects/near.ai/near-explorer/backend/node_modules/truffle-contract/lib/contract/constructorMethods.js:65:18)
    at Object.<anonymous> (/mnt/storage/projects/near.ai/near-explorer/backend/node_modules/autobahn/lib/xbr/xbr.js:62:33)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/mnt/storage/projects/near.ai/near-explorer/backend/node_modules/autobahn/lib/autobahn.js:45:11)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/mnt/storage/projects/near.ai/near-explorer/backend/node_modules/autobahn/index.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
```

What should I do about them?

Is there a way to strip all the crypto stuff from the library? (I don't plan to use it)

**Comment by tonix-tuft** [comment]
Same for me, have you found a way to fix this?

**Comment by frol** [comment]
@tonix-tuft I have downgraded to 19.4.1

**Comment by tonix-tuft** [comment]
@frol OK, thank you, I downgraded too. Will wait for this to be fixed. I am not using crypto stuff too.

**Comment by oberstet** [comment]
rgd the "big fat dependency": https://github.com/crossbario/autobahn-js/issues/436

**Comment by om26er** [comment]
fixed via https://github.com/crossbario/autobahn-js/pull/439

**Comment by tonix-tuft** [comment]
I tried to run `npm update` again and I still see the error.  Also, running `npm install` gives the following error:

```
npm ERR! path /path/app/node_modules/websocket
npm ERR! code EISGIT
npm ERR! git /path/app/node_modules/websocket: Appears to be a git repo or submodule.
npm ERR! git     /path/app/node_modules/websocket
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2019-06-14T07_53_01_721Z-debug.log
```

Autobahn version after `npm update` is 19.6.1.

Have your changes been incorporated into this most recent version?

**Comment by tonix-tuft** [comment]
@om26er  I saw that your changes on master haven't been tagged yet. Will wait for the new version. Until that I am gonna stick to version 19.4.1 as @frol suggested.

**Comment by om26er** [comment]
I just released v19.6.2, which fixes that issue.
